# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency
remote_theme: mmarchioro/agency-jekyll-theme

url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: Quant Island
email: qisiteforms@quantisland.com #this is also the email contact forms will go to
description: "Quantitative Finance services for Venture Capitalists and Web3 Startups"
author: Marco Marchioro
logo: #optional, defaults to site title
  path: assets\img\clients\Logo_Left_Of_Text.png
  height: 52 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# Submission can be seen at: https://formspree.io/forms/xnqwrygw/integration

formspree_form_path: "f/xnqwrygw"

# Use https://realfavicongenerator.net/ to generate your package
favicon_package: "assets/favicon_package"

plugins:
  - jekyll-remote-theme

# Location of pdf files
defaults:
  - scope:
      path: "assets/pdf"
    values:
      image: false
